services:
  frontend:
    build:
      context: .
      dockerfile: ${BUILD_MODE:-development}.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    stdin_open: ${STDIN_OPEN:-true}  # Enable stdin_open in development for React DevTools, disable in production
    command: sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then serve -s dist -l 3000; else npm install && npm run dev -- --host; fi"
    depends_on:
      - ibeam
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ibeam:
    image: voyz/ibeam
    ports:
      - "5055:5000" # 5000 is busy in MacOS, directing local port 5055 to docker port 5000
    env_file:
      - .env
    # environment:
    #   - TWS_HOST=host.docker.internal
    #   - TWS_PORT=7497
    #   - READONLY=false
    volumes:
      - ./inputs/conf.yaml:/srv/inputs/conf.yaml
      # - ./inputs/cacert.pem:/srv/inputs/cacert.pem # Not using cacert yet
      # - ./inputs/cacert.jks:/srv/inputs/cacert.jks # Not using cacert yet
    network_mode: bridge # Required due to clientportal.gw IP whitelist
    restart: "no" # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "-k", "-f", "http://localhost:5055/v1/api/one/user"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s